set_volume:
  description: Set the volume of the PC.
  fields:
    volume_level:
      description: The volume level (0.0 to 1.0).
      example: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
mute:
  description: Mute or unmute the PC.
lock:
  description: Lock the PC.
