set_volume:
  description: Sets the volume of the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"
    volume_level:
      description: The volume level to set (0.0 to 1.0).
      example: 0.5

mute:
  description: Mutes or unmutes the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"

lock:
  description: Toggles the enforced lock for the PC (enables/disables automatic re-locking).
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"
