set_volume:
  description: Sets the volume of the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"
    volume_level:
      description: The volume level to set (0.0 to 1.0).
      example: 0.5

mute:
  description: Mutes or unmutes the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"

lock:
  description: Locks the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"

enforce_lock:
  description: Enables or disables the enforced lock for the PC.
  fields:
    entity_id:
      description: The entity ID of the PC.
      example: "pc.felixlaptop"
    enabled:
      description: Whether to enable or disable the enforced lock.
      example: true
