turn_on:
  name: Turn On
  description: Turns on the PC device.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the PC device to turn on.
      required: true
      selector:
        entity:
          integration: pc

turn_off:
  name: Turn Off
  description: Turns off the PC device.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the PC device to turn off.
      required: true
      selector:
        entity:
          integration: pc

set_volume_level:
  name: Set Volume Level
  description: Sets the volume level of the PC device.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the PC device.
      required: true
      selector:
        entity:
          integration: pc
    volume_level:
      name: Volume Level
      description: The volume level to set (0.0 to 1.0).
      required: true
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01

toggle_mute:
  name: Toggle Mute
  description: Toggles the mute state of the PC device.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the PC device.
      required: true
      selector:
        entity:
          integration: pc

toggle_enforce_lock:
  name: Toggle Enforce Lock
  description: Toggles the enforced lock state of the PC device.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the PC device.
      required: true
      selector:
        entity:
          integration: pc
